language: cpp
sudo: required
dist: xenial
compiler:
  - gcc
os:
  - linux
  - osx
  - windows
before_install:
  - git clone https://github.com/microsoft/vcpkg.git
  - cd vcpkg
  - if [ $TRAVIS_OS_NAME == linux ]; then ./bootstrap-vcpkg.sh && sudo ./vcpkg integrate install; fi
  